import { Rule } from "../types";

export const VIP_DOMAINS = ["ceo", "cto", "founder", "executive", "vp", "director"];

export function buildBuiltinRules(): Rule[] {
  return [
    {
      id: "vip-sender",
      name: "VIP Sender",
      description: "Messages from VIP contacts are Critical priority",
      category: "important",
      executionOrder: 10,
      conditions: [{ field: "sender.isVIP", operator: "equals", value: true }],
      actions: [{ type: "setPriority", value: "critical" }, { type: "adjustScore", value: 30 }],
      enabled: true,
      userOverridable: true,
    },
    {
      id: "starred-message",
      name: "Starred / Flagged Message",
      description: "Starred or flagged messages are High priority",
      category: "important",
      executionOrder: 20,
      conditions: [{ field: "isStarred", operator: "equals", value: true }],
      actions: [{ type: "setPriority", value: "high" }, { type: "adjustScore", value: 25 }],
      enabled: true,
      userOverridable: true,
    },
    {
      id: "invoice-detected",
      name: "Invoice / Payment Detected",
      description: "Emails containing invoice or payment keywords",
      category: "important",
      executionOrder: 30,
      conditions: [
        { field: "category", operator: "equals", value: "email" },
        { field: "title", operator: "regex", value: "invoice|payment|bill|receipt|due|overdue" },
      ],
      actions: [{ type: "setPriority", value: "high" }, { type: "adjustScore", value: 20 }, { type: "addTag", value: "financial" }],
      enabled: true,
      userOverridable: true,
    },
    {
      id: "security-alert",
      name: "Security Alert",
      description: "Security-related alerts and notifications",
      category: "important",
      executionOrder: 5,
      conditions: [
        { field: "title", operator: "regex", value: "security|breach|unauthorized|suspicious|login|password|2fa|mfa|vulnerability" },
      ],
      actions: [{ type: "setPriority", value: "critical" }, { type: "adjustScore", value: 40 }, { type: "markRisk", value: true }],
      enabled: true,
      userOverridable: true,
    },
    {
      id: "executive-communication",
      name: "Executive Communication",
      description: "Communications from executives or leadership",
      category: "important",
      executionOrder: 15,
      conditions: [
        {
          field: "sender.domain",
          operator: "regex",
          value: VIP_DOMAINS.join("|"),
        },
      ],
      actions: [{ type: "setPriority", value: "high" }, { type: "adjustScore", value: 25 }],
      enabled: true,
      userOverridable: true,
    },
    {
      id: "client-escalation",
      name: "Client Escalation",
      description: "Client messages with urgent keywords",
      category: "important",
      executionOrder: 8,
      conditions: [
        { field: "sender.isClient", operator: "equals", value: true },
        { field: "title", operator: "regex", value: "urgent|escalat|critical|asap|blocker|emergency" },
      ],
      actions: [{ type: "setPriority", value: "critical" }, { type: "adjustScore", value: 35 }, { type: "markRisk", value: true }],
      enabled: true,
      userOverridable: true,
    },
    {
      id: "project-deadline",
      name: "Project Deadline Approaching",
      description: "Meetings and tasks with approaching deadlines",
      category: "priority",
      executionOrder: 25,
      conditions: [
        { field: "category", operator: "in", value: ["meeting", "task"] },
      ],
      actions: [{ type: "setPriority", value: "high" }, { type: "adjustScore", value: 20 }],
      enabled: true,
      userOverridable: true,
    },
    {
      id: "unanswered-4h",
      name: "Unanswered Message (4h+)",
      description: "Messages awaiting reply for over 4 hours",
      category: "followup",
      executionOrder: 35,
      conditions: [
        { field: "isUnread", operator: "equals", value: true },
      ],
      actions: [{ type: "markFollowUp", value: true }, { type: "adjustScore", value: 15 }],
      enabled: true,
      userOverridable: true,
    },
    {
      id: "pending-pr-review",
      name: "Pending PR Review",
      description: "GitHub pull requests awaiting review",
      category: "followup",
      executionOrder: 30,
      conditions: [
        { field: "platform", operator: "equals", value: "github" },
        { field: "metadata.github.isReviewRequested", operator: "equals", value: true },
      ],
      actions: [{ type: "markFollowUp", value: true }, { type: "adjustScore", value: 20 }, { type: "addTag", value: "code-review" }],
      enabled: true,
      userOverridable: true,
    },
    {
      id: "direct-mention",
      name: "Direct Mention / DM",
      description: "Direct messages or @mentions",
      category: "priority",
      executionOrder: 40,
      conditions: [
        {
          field: "metadata.slack.isMention",
          operator: "equals",
          value: true,
        },
      ],
      actions: [{ type: "adjustScore", value: 15 }],
      enabled: true,
      userOverridable: true,
    },
    {
      id: "has-attachments",
      name: "Has Attachments",
      description: "Messages with file attachments need review",
      category: "priority",
      executionOrder: 45,
      conditions: [
        { field: "metadata.gmail.hasAttachments", operator: "equals", value: true },
      ],
      actions: [{ type: "adjustScore", value: 10 }],
      enabled: true,
      userOverridable: true,
    },
    {
      id: "build-failure",
      name: "Build / Deployment Failure",
      description: "Failed builds or deployments",
      category: "risk",
      executionOrder: 3,
      conditions: [
        { field: "title", operator: "regex", value: "fail|error|crash|down|outage|degred" },
        { field: "platform", operator: "in", value: ["github", "slack", "telegram"] },
      ],
      actions: [{ type: "setPriority", value: "critical" }, { type: "adjustScore", value: 40 }, { type: "markRisk", value: true }],
      enabled: true,
      userOverridable: true,
    },
    {
      id: "calendar-conflict",
      name: "Calendar Conflict",
      description: "Overlapping calendar events",
      category: "risk",
      executionOrder: 50,
      conditions: [
        { field: "platform", operator: "equals", value: "calendar" },
        { field: "category", operator: "equals", value: "meeting" },
      ],
      actions: [{ type: "adjustScore", value: 10 }, { type: "addTag", value: "meeting" }],
      enabled: true,
      userOverridable: true,
    },
    {
      id: "newsletter-promo",
      name: "Newsletter / Promotion",
      description: "Newsletters and promotional emails — lower priority",
      category: "informational",
      executionOrder: 100,
      conditions: [
        { field: "metadata.gmail.isPromo", operator: "equals", value: true },
      ],
      actions: [{ type: "setPriority", value: "low" }, { type: "adjustScore", value: -20 }],
      enabled: true,
      userOverridable: true,
    },
  ];
}
